import type { ReactNode } from 'react';
import dayClear from '../assets/illustrations/day-clear.svg?raw';
import inboxEmpty from '../assets/illustrations/inbox-empty.svg?raw';
import listEmpty from '../assets/illustrations/list-empty.svg?raw';
import notFound from '../assets/illustrations/not-found.svg?raw';
import weekFree from '../assets/illustrations/week-free.svg?raw';

/**
 * Lucide marks, generated by `tools/illustrations.mjs`. Lucide is the same
 * drawing language as this app's own icon set, so an empty state shows the icon
 * system at a larger size rather than foreign artwork pasted in.
 *
 * Inlined rather than referenced as an image element, because an externally
 * loaded SVG cannot inherit `currentColor` — it would be stuck with one theme's
 * greys. The markup is generated from vetted local files and never touches user
 * input, which is what makes `dangerouslySetInnerHTML` safe here.
 *
 * Lucide is ISC; the notice travels inside each generated file. See
 * ATTRIBUTION.md and assets/lucide-LICENSE.txt.
 */
const ART = {
  'day-clear': dayClear,
  'inbox-empty': inboxEmpty,
  'list-empty': listEmpty,
  'not-found': notFound,
  'week-free': weekFree,
} as const;

export type IllustrationName = keyof typeof ART;

interface Props {
  /** Omit for failures: an error is not an empty state and gets no drawing. */
  illustration?: IllustrationName;
  title: string;
  children: ReactNode;
  action?: ReactNode;
  /** `h1` when the empty state *is* the screen, `h2` when it sits under one. */
  level?: 1 | 2;
}

export function EmptyState({ illustration, title, children, action, level = 2 }: Props) {
  const Heading = level === 1 ? 'h1' : 'h2';

  return (
    <div className="empty">
      {illustration && (
        /* Decorative: the sentence below carries the meaning, so the drawing is
           hidden from assistive tech rather than described twice. */
        <div className="empty__illo" aria-hidden="true" dangerouslySetInnerHTML={{ __html: ART[illustration] }} />
      )}
      <Heading className="empty__title">{title}</Heading>
      <p className="empty__body">{children}</p>
      {action}
    </div>
  );
}
